Controllers/adminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class adminController : Controller
    {
        private DatabaseEntities db = new DatabaseEntities();

        // GET: admin/dashboard
        public ActionResult index()
        {
            if (Session["admId"] == null)
            {
                return RedirectToAction("login");
            }
            return View(new megalist() { user = db.users.Find(Session["userID"]) });
        }

        public ActionResult login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult login(string userAccount, string userPassword)
        {
            if (ModelState.IsValid)
            {
                users user = null;
                switch (IdentifyInput(userAccount))
                {
                    case "Email":
                        user = db.users.FirstOrDefault(u => u.userEmail.Equals(userAccount));
                        break;
                    case "Phone Number":
                        user = db.users.FirstOrDefault(u => u.userPhone.Equals(userAccount));
                        break;
                    case "Username":
                        user = db.users.FirstOrDefault(u => u.username.Equals(userAccount));
                        break;
                    default:
                        ViewBag.ToastType = "Error";
                        ViewBag.ToastMsg = "Undentify account!";
                        return View();
                }

                if (user != null && user.roleID == 1)
                {
                    if (Crypto.VerifyHashedPassword(user.userPassword, userPassword))
                    {
                        Session["admId"] = Guid.NewGuid().ToString();
                        Session["userID"] = user.userID;
                        Session["userfullname"] = user.userFullName;

                        return RedirectToAction("index");
                    }
                    else
                    {
                        ViewBag.ToastType = "Error";
                        ViewBag.ToastMsg = "Wrong password!";
                        return View();
                    }
                }
                else
                {
                    ViewBag.ToastType = "Error";
                    ViewBag.ToastMsg = "You don't have permission!";
                    return View();
                }
            }
            return null;
        }

        [HttpGet]
        public ActionResult logout()
        {
            if (Session["admId"] != null)
            {
                FormsAuthentication.SignOut();
                Session.Clear();
                Session.Contents.Clear();
                Session.RemoveAll();
                Session.Abandon();

                return RedirectToAction("index");
            }
            else
            {
                return View("~/Views/Layouts/error.cshtml");
            }
        }

        public string IdentifyInput(string input)
        {
            // Regex for email
            var emailRegex = new Regex(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$");
            // Regex for phone number (simplified)
            //var phoneRegex = new Regex(@"^\d{12}$");
            var phoneRegex = new Regex(@"^\+\d{1,3}\s?\(?\d{1,3}\)?[\s.-]?\d{1,4}[\s.-]?\d{1,9}$");

            if (emailRegex.IsMatch(input))
            {
                // Check if email exists in the database
                users user = db.users.FirstOrDefault(u => u.userEmail == input);
                return user != null ? "Email" : "Unknown";
            }
            else if (phoneRegex.IsMatch(input))
            {
                // Check if phone number exists in the database
                users user = db.users.FirstOrDefault(u => u.userPhone == input);
                return user != null ? "Phone Number" : "Unknown";
            }
            else
            {
                // Check if username exists in the database
                users user = db.users.FirstOrDefault(u => u.username == input);
                return user != null ? "Username" : "Unknown";
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/admin/login.cshtml
@model WebApplication.Models.users
@{
    ViewBag.Title = "Login";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<!-- [Head] start -->
<head>
    <title>Login | Admin Dashboard</title>
    <!-- [Meta] -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0,minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- [Favicon] icon -->
    <link rel="icon" href="~/Content/assets/images/favicon.svg" type="image/x-icon">
    <!-- [Google Font : Public Sans] icon -->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
    <!-- [Tabler Icons] https://tablericons.com -->
    <link rel="stylesheet" href="~/Content/assets/fonts/tabler-icons.min.css">
    <!-- [Feather Icons] https://feathericons.com -->
    <link rel="stylesheet" href="~/Content/assets/fonts/feather.css">
    <!-- [Font Awesome Icons] https://fontawesome.com/icons -->
    <link rel="stylesheet" href="~/Content/assets/fonts/fontawesome.css">
    <!-- [Material Icons] https://fonts.google.com/icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/material-icons@1.13.12/iconfont/material-icons.min.css">
    <!-- [Template CSS Files] -->
    <link rel="stylesheet" href="~/Content/assets/css/style.css" id="main-style-link">
    <link rel="stylesheet" href="~/Content/assets/css/style-preset.css">
</head>
<!-- [Head] end -->
<!-- [Body] Start -->
<body data-pc-preset="preset-1" data-pc-sidebar-theme="dark" data-pc-sidebar-caption="true" data-pc-direction="ltr" data-pc-theme="light">
    <!-- [ Pre-loader ] start -->
    <div class="loader-bg">
        <div class="pc-loader">
            <div class="loader-fill"></div>
        </div>
    </div>
    <!-- [ Pre-loader ] End -->
    <div class="auth-main v1">
        <div class="bg-overlay bg-white"></div>
        <div class="auth-wrapper">
            <div class="auth-form">
                <a href="/" class="d-block mt-5">
                    <img src="~/Content/assets/images/logo-white.svg" alt="img">
                </a>
                <div class="card mb-5 mt-3">
                    <div class="card-header bg-dark">
                        <h4 class="text-center text-white f-w-500 mb-0">Login with your email</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="@Url.Action("login", "admin")">
                            @Html.AntiForgeryToken()
                            <div class="form-group mb-3">
                                @Html.TextBoxFor(m => m.userAccount, new { @class = "form-control", @placeholder = "Email or Username", @required = "required" })
                                @Html.ValidationMessageFor(m => m.userAccount, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group mb-3">
                                @Html.PasswordFor(m => m.userPassword, new { @class = "form-control", @placeholder = "Password", @required = "required" })
                                @Html.ValidationMessageFor(m => m.userPassword, "", new { @class = "text-danger" })
                            </div>
                            <div class="d-flex mt-1 justify-content-between align-items-center">
                                <div class="form-check">
                                    <input class="form-check-input input-primary" type="checkbox" id="customCheckc1" checked="">
                                    <label class="form-check-label text-muted" for="customCheckc1">Remember me?</label>
                                </div>
                            </div>
                            <div class="d-grid mt-4">
                                <button type="submit" class="btn btn-primary">Login</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- [ Main Content ] end -->
    <!-- Required Js -->
    <script src="~/Content/assets/js/plugins/popper.min.js"></script>
    <script src="~/Content/assets/js/plugins/simplebar.min.js"></script>
    <script src="~/Content/assets/js/plugins/bootstrap.min.js"></script>
    <script src="~/Content/assets/js/fonts/custom-font.js"></script>
    <script src="~/Content/assets/js/pcoded.js"></script>
    <script src="~/Content/assets/js/plugins/feather.min.js"></script>
</body>
<!-- [Body] end -->
</html>